# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161012_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visited',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 16, 11, 0, 28, 701632, tzinfo=utc)),
        ),
    ]
